---
name: Catalyst-Plugin-Devel-InPageLogs
version: 0.01_01
author:
  - Thomas L. Shinnick <tshinnic@cpan.org>
abstract: Append Catalyst request debug messages to output web page
license: perl
requires:
  Catalyst: 5.10
  Data::Dumper: 0
  Test::More: 0
provides:
  Catalyst::Plugin::Devel::InPageLogs:
    file: lib/Catalyst/Plugin/Devel/InPageLogs.pm
    version: 0.01_01
  Catalyst::Plugin::Devel::InPageLogs::Log:
    file: lib/Catalyst/Plugin/Devel/InPageLogs/Log.pm
    version: 0.01_01
generated_by: Module::Build version 0.2611
